import {
  ArrowDownLeft,
  ArrowLeftRight,
  Building2,
  CreditCard,
  DollarSign,
  Plus,
  Settings,
  Smartphone,
  Store,
  Undo2,
  Zap,
} from 'lucide-react'
import type { TransactionTypeConfig } from './types'

export const INTERNAL_TRANSACTION_TYPES: Record<string, TransactionTypeConfig> = {
  WALLET_TO_WALLET: {
    name: 'Wallet to Wallet',
    description: 'RukaPay to RukaPay transfers',
    icon: CreditCard,
    color: 'bg-blue-500',
    tabId: 'wallet-to-wallet',
  },
  WALLET_TO_INTERNAL_MERCHANT: {
    name: 'Wallet to Internal Merchant',
    description: 'Payments to RukaPay merchants',
    icon: Store,
    color: 'bg-indigo-500',
    tabId: 'wallet-to-internal-merchant',
  },
  WALLET_INIT: {
    name: 'Wallet Initialization',
    description: 'Fee for initializing wallets',
    icon: Plus,
    color: 'bg-emerald-600',
    tabId: 'wallet-init',
  },
  FEE_CHARGE: {
    name: 'Fee Charge',
    description: 'Transaction fee charges',
    icon: DollarSign,
    color: 'bg-purple-500',
    tabId: 'fee-charge',
  },
  REVERSAL: {
    name: 'Reversal',
    description: 'Transaction reversals',
    icon: Undo2,
    color: 'bg-red-600',
    tabId: 'reversal',
  },
  CUSTOM: {
    name: 'Custom',
    description: 'Custom transaction types',
    icon: Settings,
    color: 'bg-gray-600',
    tabId: 'custom-internal',
  },
}

export const EXTERNAL_TRANSACTION_TYPES: Record<string, TransactionTypeConfig> = {
  DEPOSIT: {
    name: 'Deposit',
    description: 'Deposits into RukaPay wallet',
    icon: ArrowDownLeft,
    color: 'bg-emerald-500',
    tabId: 'deposit',
  },
  WITHDRAWAL: {
    name: 'Withdrawal',
    description: 'Withdrawals from RukaPay wallet',
    icon: CreditCard,
    color: 'bg-red-500',
    tabId: 'withdrawal',
  },
  WALLET_TO_MNO: {
    name: 'Wallet to MNO',
    description: 'Disbursement to MTN/AIRTEL',
    icon: Smartphone,
    color: 'bg-green-500',
    tabId: 'wallet-to-mno',
  },
  WALLET_TO_EXTERNAL_MERCHANT: {
    name: 'Wallet to External Merchant',
    description: 'Payments to external merchants',
    icon: Store,
    color: 'bg-purple-500',
    tabId: 'wallet-to-external-merchant',
  },
  BANK_TO_WALLET: {
    name: 'Bank to Wallet',
    description: 'Bank transfers to wallet',
    icon: Building2,
    color: 'bg-orange-500',
    tabId: 'bank-to-wallet',
  },
  MNO_TO_WALLET: {
    name: 'MNO to Wallet',
    description: 'Mobile money collections',
    icon: Smartphone,
    color: 'bg-blue-500',
    tabId: 'mno-to-wallet',
  },
  WALLET_TO_BANK: {
    name: 'Wallet to Bank',
    description: 'Wallet to bank transfers',
    icon: Building2,
    color: 'bg-amber-500',
    tabId: 'wallet-to-bank',
  },
  WALLET_TO_UTILITY: {
    name: 'Wallet to Utility',
    description: 'Utility bill payments',
    icon: Zap,
    color: 'bg-yellow-600',
    tabId: 'wallet-to-utility',
  },
  BILL_PAYMENT: {
    name: 'Bill Payment',
    description: 'Utility bills via partners',
    icon: Zap,
    color: 'bg-purple-600',
    tabId: 'bill-payment',
  },
  SCHOOL_FEES: {
    name: 'School Fees',
    description: 'School fees payments',
    icon: Zap,
    color: 'bg-blue-600',
    tabId: 'school-fees',
  },
  MERCHANT_WITHDRAWAL: {
    name: 'Merchant Withdrawal',
    description: 'Merchant payouts',
    icon: DollarSign,
    color: 'bg-amber-600',
    tabId: 'merchant-withdrawal',
  },
  MERCHANT_TO_WALLET: {
    name: 'Merchant to Wallet',
    description: 'Merchant to wallet transfers',
    icon: ArrowLeftRight,
    color: 'bg-teal-600',
    tabId: 'merchant-to-wallet',
  },
  CARD_TO_WALLET: {
    name: 'Card to Wallet',
    description: 'Card payments to wallet',
    icon: CreditCard,
    color: 'bg-cyan-600',
    tabId: 'card-to-wallet',
  },
  WALLET_TO_PARTNER_INSTITUTION: {
    name: 'Wallet → Partner Institution',
    description: 'SACCO / institution settlement',
    icon: Building2,
    color: 'bg-teal-700',
    tabId: 'wallet-to-partner-institution',
  },
  PARTNER_INSTITUTION_TO_WALLET: {
    name: 'Partner Institution → Wallet',
    description: 'Institution payout to wallet',
    icon: Building2,
    color: 'bg-sky-700',
    tabId: 'partner-institution-to-wallet',
  },
  CUSTOM: {
    name: 'Custom',
    description: 'Custom partner modes',
    icon: Settings,
    color: 'bg-indigo-600',
    tabId: 'custom',
  },
}

export const TRANSACTION_TYPE_LABELS: Record<string, string> = {
  WALLET_TO_INTERNAL_MERCHANT: 'Wallet to Internal Merchant',
  WALLET_TO_WALLET: 'Wallet to Wallet',
  WALLET_INIT: 'Wallet Initialization',
  WALLET_CREATION: 'Wallet Initialization',
  FEE_CHARGE: 'Fee Charge',
  REVERSAL: 'Reversal',
  DEPOSIT: 'Deposit',
  WITHDRAWAL: 'Withdrawal',
  WALLET_TO_MNO: 'Wallet to MNO',
  WALLET_TO_EXTERNAL_MERCHANT: 'Wallet to External Merchant',
  BANK_TO_WALLET: 'Bank to Wallet',
  MNO_TO_WALLET: 'MNO to Wallet',
  WALLET_TO_BANK: 'Wallet to Bank',
  WALLET_TO_UTILITY: 'Wallet to Utility',
  WALLET_TO_MERCHANT: 'Wallet to Merchant',
  BILL_PAYMENT: 'Bill Payment',
  SCHOOL_FEES: 'School Fees',
  MERCHANT_WITHDRAWAL: 'Merchant Withdrawal',
  MERCHANT_TO_WALLET: 'Merchant to Wallet',
  CARD_TO_WALLET: 'Card to Wallet',
  WALLET_TO_PARTNER_INSTITUTION: 'Wallet to Partner Institution',
  PARTNER_INSTITUTION_TO_WALLET: 'Partner Institution to Wallet',
  CUSTOM: 'Custom',
}
